# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='key',
            field=models.TextField(default=b' '),
        ),
    ]
