# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
