# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160409_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
