# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imagelink',
            field=models.TextField(default=b' '),
        ),
    ]
